export const POST_RECIPE_STARTED = 'POST_RECIPE_STARTED';
export const POST_RECIPE_FAILURE = 'POST_RECIPE_FAILURE';
export const POST_RECIPE_SUCCESS = 'POST_RECIPE_SUCCESS';

export const GET_RECIPE_STARTED = 'GET_RECIPE_STARTED';
export const GET_RECIPE_FAILURE = 'GET_RECIPE_FAILURE';
export const GET_RECIPE_SUCCESS = 'GET_RECIPE_SUCCESS';

export const GET_RECIPES_STARTED = 'GET_RECIPES_STARTED';
export const GET_RECIPES_FAILURE = 'GET_RECIPES_FAILURE';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';

export const ADD_RECIPE_STARTED = 'ADD_RECIPE_STARTED';
export const ADD_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';

export const SET_DOMAIN = 'SET_DOMAIN';
export const SET_DOMAINS = 'SET_DOMAINS';
export const SET_PREVIWES = 'SET_PREVIWES';

export const SET_COMPONENTS_PREVIEW = 'SET_COMPONENTS_PREVIEW';

export const SET_RECIPE_DIFFICULTY = 'SET_RECIPE_DIFFICULTY';
export const SET_PORTION_COUNT = 'SET_PORTION_COUNT';

export const ADD_RECIPE__COMPONENT = 'ADD_RECIPE__COMPONENT';
export const REMOVE_RECIPE__COMPONENT = 'REMOVE_RECIPE__COMPONENT';
export const ADD_RECIPE__PROGRESS_STEP = 'ADD_RECIPE__PROGRESS_STEP';
export const SET_BASIC_INFO = 'SET_BASIC_INFO';

export const ADD_COMPONENT_TO_ADVANCED_SEARCH_LIST = 'ADD_COMPONENT_TO_ADVANCED_SEARCH_LIST';
export const REMOVE_COMPONENT_FROM_ADVANCED_SEARCH_LIST =
'REMOVE_COMPONENT_FROM_ADVANCED_SEARCH_LIST';


export const CLEAR__ADVANCED_SEARCH = 'CLEAR__ADVANCED_SEARCH';

export const SHOW_MENU = 'SHOW_MENU';
export const HIDE_MENU = 'HIDE_MENU';

export const SHOW_ADVANCEDSEARCH = 'SHOW_ADVANCEDSEARCH';
export const HIDE_ADVANCEDSEARCH = 'HIDE_ADVANCEDSEARCH';
